//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacaoFaculdade.Views {
	
	
	public partial class Usuarios {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.GridView userGridView;
		
		protected System.Web.UI.WebControls.LinkButton editButton;
		
		protected System.Web.UI.WebControls.LinkButton delButton;
	}
}
